"""create likes table

Revision ID: 340e76619a62
Revises: 3f213dc626f1
Create Date: 2018-09-28 21:09:07.009062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340e76619a62'
down_revision = '3f213dc626f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
